replicaCount: 1
namespace: default
container:
  image: mongo
  tag: 4.4.6
persistence:
  size: 1Gi
  accessMode: ReadWriteOnce
secret:
  root_username: c3VoYWlsMTI=
  root_password: c3VoYWlsMzQ=
  username: c3VoYWlsMTI=
  password: c3VoYWlsMzQ=
  users_list: c3VoYWlsMTI=
matchExpressions:
  values: kubernetes-control-plane
